Remove module download
This should fix the errors in the hermetic image build:

```
[1/2] STEP 7/14: RUN go mod download
Go compliance shim [449] [rhel-8-golang-1.22][openshift-golang-builder]: assessment: CGO_ENABLED=1
Go compliance shim [449] [rhel-8-golang-1.22][openshift-golang-builder]: assessment: dynamic linking
Go compliance shim [449] [rhel-8-golang-1.22][openshift-golang-builder]: skipping forced compliance due to broad exemption
Go compliance shim [449] [rhel-8-golang-1.22][openshift-golang-builder]: EXEMPT: 1

Go compliance shim [449] [rhel-8-golang-1.22][openshift-golang-builder]: final command line arguments: "mod" "download"

Go compliance shim [449] [rhel-8-golang-1.22][openshift-golang-builder]: invoking real go binary
go: cloud.google.com/go/auth@v0.7.2: Get "https://proxy.golang.org/cloud.google.com/go/auth/@v/v0.7.2.mod": dial tcp: lookup proxy.golang.org on 172.30.0.10:53: dial udp 172.30.0.10:53: connect: network is unreachable
Go compliance shim [449] [rhel-8-golang-1.22][openshift-golang-builder]: Exited with: 1
subprocess exited with status 1
subprocess exited with status 1
Error: building at STEP "RUN go mod download": exit status 1
```

Dockerfile fixup